"""
Report Generator Skill - Generate formatted reports in Google Docs
"""

from typing import List, Optional
from datetime import datetime
from loguru import logger

from utils.google.docs_client import docs_client
from utils.google.drive_client import drive_client
from models.stakeholder import StakeholderProfile
from models.insight import Theme, Conflict, Quote
from models.relationship import InfluenceMatrix
from models.action import ActionItem
from models.report import InsightSummary, DiscoveryReport
from config import settings


class ReportGenerator:
    """
    Skill for generating formatted reports in Google Docs.

    Capabilities:
    - Generate stakeholder discovery reports
    - Create executive briefs
    - Generate individual stakeholder summaries
    - Format insights for presentation
    """

    def __init__(self):
        self.docs = docs_client
        self.drive = drive_client

    def generate_discovery_report(
        self,
        title: str,
        profiles: List[StakeholderProfile],
        insight_summary: InsightSummary,
        influence_matrix: Optional[InfluenceMatrix] = None,
        themes: Optional[List[Theme]] = None,
        conflicts: Optional[List[Conflict]] = None,
        folder_id: Optional[str] = None,
    ) -> DiscoveryReport:
        """
        Generate a complete stakeholder discovery report.

        Args:
            title: Report title
            profiles: List of stakeholder profiles
            insight_summary: Aggregated insights summary
            influence_matrix: Optional influence matrix
            themes: Optional list of themes
            conflicts: Optional list of conflicts
            folder_id: Folder to save report in

        Returns:
            DiscoveryReport object with Google Doc reference
        """
        logger.info(f"Generating discovery report: {title}")

        # Build report object
        report = DiscoveryReport(
            title=title,
            generated_at=datetime.utcnow(),
            insight_summary=insight_summary,
            stakeholder_profiles=profiles,
            influence_matrix=influence_matrix,
            themes_and_patterns=themes or [],
            conflicts_and_risks=conflicts or [],
        )

        # Generate executive summary
        report.executive_summary = report.generate_executive_summary()

        # Build document content
        content = self._build_report_content(report)

        # Create Google Doc
        doc_id = self.docs.create_document(
            title=f"Stakeholder Discovery Report - {title}",
            content=content,
            folder_id=folder_id,
        )

        if doc_id:
            report.google_doc_id = doc_id
            report.google_doc_url = f"https://docs.google.com/document/d/{doc_id}"
            logger.info(f"Created report document: {report.google_doc_url}")
        else:
            logger.warning("Failed to create Google Doc for report")

        return report

    def _build_report_content(self, report: DiscoveryReport) -> str:
        """Build the full report content as text"""
        sections = []

        # Title
        sections.append(f"# {report.title}")
        sections.append(f"\nGenerated: {report.generated_at.strftime('%B %d, %Y')}")
        sections.append(f"Generated by: {report.generated_by}")
        sections.append("\n---\n")

        # Executive Summary
        sections.append("# Executive Summary")
        sections.append(report.executive_summary)
        sections.append("\n---\n")

        # Overview
        if report.insight_summary:
            sections.append("# Overview")
            sections.append(f"\n- **Total Stakeholders:** {report.insight_summary.total_stakeholders}")
            sections.append(f"- **Total Interactions:** {report.insight_summary.total_interactions}")

            if report.insight_summary.stance_breakdown:
                sections.append("\n## Stakeholder Sentiment Distribution")
                for stance, count in report.insight_summary.stance_breakdown.items():
                    sections.append(f"- {stance.title()}: {count}")

            sections.append("\n---\n")

        # Stakeholder Profiles
        if report.stakeholder_profiles:
            sections.append("# Stakeholder Profiles")

            for profile in report.stakeholder_profiles:
                sections.append(f"\n## {profile.name}")
                sections.append(f"**Role:** {profile.role}")
                sections.append(f"**Department:** {profile.department}")
                sections.append(f"**Influence Level:** {profile.influence_level.value}")
                sections.append(f"**Stance:** {profile.stance.value}")

                if profile.top_concerns:
                    sections.append("\n### Top Concerns")
                    for c in profile.top_concerns[:3]:
                        sections.append(f"- {c.description}")

                if profile.top_needs:
                    sections.append("\n### Top Needs")
                    for n in profile.top_needs[:3]:
                        sections.append(f"- {n.description}")

                if profile.highlight_quotes:
                    sections.append("\n### Key Quotes")
                    for q in profile.highlight_quotes[:2]:
                        sections.append(f'> "{q.text}"')

            sections.append("\n---\n")

        # Themes and Patterns
        if report.themes_and_patterns:
            sections.append("# Themes and Patterns")

            for theme in report.themes_and_patterns:
                sections.append(f"\n## {theme.name}")
                sections.append(f"**Category:** {theme.category}")
                sections.append(f"**Severity:** {theme.severity.value}")
                sections.append(f"**Urgency:** {theme.urgency}")
                sections.append(f"\n{theme.description}")

                if theme.stakeholders:
                    sections.append(f"\n**Stakeholders:** {', '.join(theme.stakeholders)}")

                if theme.recommended_actions:
                    sections.append("\n**Recommended Actions:**")
                    for action in theme.recommended_actions:
                        sections.append(f"- {action}")

            sections.append("\n---\n")

        # Conflicts and Risks
        if report.conflicts_and_risks:
            sections.append("# Conflicts and Risks")

            for conflict in report.conflicts_and_risks:
                sections.append(f"\n## {conflict.description}")
                sections.append(f"**Parties:** {', '.join(conflict.parties)}")
                sections.append(f"**Type:** {conflict.conflict_type}")
                sections.append(f"**Severity:** {conflict.severity.value}")
                sections.append(f"**Status:** {conflict.resolution_status}")

                if conflict.impact_on_initiative:
                    sections.append(f"\n**Impact:** {conflict.impact_on_initiative}")

                if conflict.resolution_approach:
                    sections.append(f"\n**Resolution Approach:** {conflict.resolution_approach}")

            sections.append("\n---\n")

        # Influence Matrix Summary
        if report.influence_matrix:
            sections.append("# Influence Analysis")

            if report.influence_matrix.power_brokers:
                sections.append("\n## Power Brokers")
                sections.append("(Highest influence individuals)")
                for name in report.influence_matrix.power_brokers:
                    sections.append(f"- {name}")

            if report.influence_matrix.bridge_builders:
                sections.append("\n## Bridge Builders")
                sections.append("(Connect different groups)")
                for name in report.influence_matrix.bridge_builders:
                    sections.append(f"- {name}")

            if report.influence_matrix.clusters:
                sections.append("\n## Stakeholder Clusters")
                for cluster in report.influence_matrix.clusters:
                    sections.append(f"\n### {cluster.name}")
                    sections.append(f"**Members:** {', '.join(cluster.members)}")
                    sections.append(f"**Overall Stance:** {cluster.overall_stance.value}")
                    if cluster.engagement_strategy:
                        sections.append(f"**Engagement Strategy:** {cluster.engagement_strategy}")

            sections.append("\n---\n")

        # Recommendations
        if report.recommendations or (report.insight_summary and report.insight_summary.strategic_recommendations):
            sections.append("# Recommendations")

            recs = report.recommendations or report.insight_summary.strategic_recommendations
            for i, rec in enumerate(recs, 1):
                sections.append(f"{i}. {rec}")

            sections.append("\n---\n")

        # Action Plan
        if report.action_plan or (report.insight_summary and report.insight_summary.immediate_actions):
            sections.append("# Action Plan")

            actions = report.action_plan or report.insight_summary.immediate_actions
            for action in actions:
                due = action.due_date.strftime("%Y-%m-%d") if action.due_date else "TBD"
                sections.append(f"- [ ] **{action.title}** (Due: {due})")
                if action.stakeholder:
                    sections.append(f"  - Stakeholder: {action.stakeholder}")
                if action.owner:
                    sections.append(f"  - Owner: {action.owner}")

        return "\n".join(sections)

    def generate_executive_brief(
        self,
        insight_summary: InsightSummary,
        profiles: List[StakeholderProfile],
        folder_id: Optional[str] = None,
    ) -> Optional[str]:
        """
        Generate a short executive brief.

        Args:
            insight_summary: Aggregated insights
            profiles: Stakeholder profiles
            folder_id: Folder to save in

        Returns:
            Google Doc ID or None
        """
        logger.info("Generating executive brief")

        # Build brief content
        content_parts = [
            "# Executive Brief - Stakeholder Discovery",
            f"\nDate: {datetime.utcnow().strftime('%B %d, %Y')}",
            f"\n## Quick Stats",
            f"- Stakeholders Analyzed: {insight_summary.total_stakeholders}",
            f"- Total Interactions: {insight_summary.total_interactions}",
        ]

        # Stance summary
        if insight_summary.stance_breakdown:
            champions = insight_summary.stance_breakdown.get("champion", 0)
            blockers = insight_summary.stance_breakdown.get("blocker", 0)
            content_parts.append(f"\n## Sentiment")
            content_parts.append(f"- Champions: {champions}")
            content_parts.append(f"- Blockers: {blockers}")

        # Top 3 concerns
        if insight_summary.top_concerns:
            content_parts.append("\n## Top Concerns")
            for c in insight_summary.top_concerns[:3]:
                content_parts.append(f"1. {c.name}")

        # Top 3 recommendations
        if insight_summary.strategic_recommendations:
            content_parts.append("\n## Key Recommendations")
            for r in insight_summary.strategic_recommendations[:3]:
                content_parts.append(f"- {r}")

        content = "\n".join(content_parts)

        return self.docs.create_document(
            title=f"Executive Brief - {datetime.utcnow().strftime('%Y-%m-%d')}",
            content=content,
            folder_id=folder_id,
        )

    def generate_stakeholder_summary(
        self,
        profile: StakeholderProfile,
        folder_id: Optional[str] = None,
    ) -> Optional[str]:
        """
        Generate a summary document for a single stakeholder.

        Args:
            profile: Stakeholder profile
            folder_id: Folder to save in

        Returns:
            Google Doc ID or None
        """
        logger.info(f"Generating summary for {profile.name}")

        content_parts = [
            f"# Stakeholder Profile: {profile.name}",
            f"\n**Role:** {profile.role}",
            f"**Department:** {profile.department}",
            f"**Influence Level:** {profile.influence_level.value}",
            f"**Stance:** {profile.stance.value}",
            f"\n**Total Interactions:** {profile.total_interactions}",
        ]

        if profile.first_contact:
            content_parts.append(f"**First Contact:** {profile.first_contact.strftime('%Y-%m-%d')}")
        if profile.last_contact:
            content_parts.append(f"**Last Contact:** {profile.last_contact.strftime('%Y-%m-%d')}")

        if profile.top_concerns:
            content_parts.append("\n## Concerns")
            for c in profile.top_concerns:
                content_parts.append(f"- {c.description} ({c.severity.value})")

        if profile.top_needs:
            content_parts.append("\n## Needs")
            for n in profile.top_needs:
                content_parts.append(f"- {n.description} ({n.priority.value})")

        if profile.goals:
            content_parts.append("\n## Goals")
            for g in profile.goals:
                content_parts.append(f"- {g}")

        if profile.highlight_quotes:
            content_parts.append("\n## Key Quotes")
            for q in profile.highlight_quotes:
                content_parts.append(f'> "{q.text}"')
                if q.context:
                    content_parts.append(f"  Context: {q.context}")

        content = "\n".join(content_parts)

        return self.docs.create_document(
            title=f"Stakeholder Profile - {profile.name}",
            content=content,
            folder_id=folder_id,
        )


# Global instance
report_generator = ReportGenerator()
